# Generated by Django 3.2 on 2021-04-21 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='showchart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.IntegerField(blank=True, max_length=4, null=True)),
                ('region', models.CharField(max_length=2, null=True)),
                ('divison', models.CharField(max_length=3, null=True)),
                ('month', models.CharField(max_length=10, null=True)),
                ('year', models.IntegerField(max_length=4, null=True)),
                ('payment', models.IntegerField(max_length=5)),
                ('bucket', models.CharField(max_length=3)),
                ('payment_mode', models.CharField(max_length=20)),
            ],
        ),
    ]
