# Generated by Django 3.2 on 2021-04-21 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showchart',
            name='customer_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='showchart',
            name='payment',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='showchart',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
