# Generated by Django 3.2 on 2021-04-21 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pie', '0003_auto_20210421_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showchart',
            name='customer_id',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='showchart',
            name='payment',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
