# Generated by Django 3.2 on 2021-04-21 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pie', '0004_auto_20210421_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showchart',
            name='customer_id',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
