# Generated by Django 3.2 on 2021-04-21 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pie', '0005_alter_showchart_customer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showchart',
            name='customer_id',
            field=models.IntegerField(null=True),
        ),
    ]
