# Generated by Django 3.2 on 2021-04-22 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pie', '0006_alter_showchart_customer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showchart',
            name='bucket',
            field=models.CharField(choices=[('<D', '<D'), ('D', 'D'), ('>D', '>D')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='showchart',
            name='divison',
            field=models.CharField(choices=[('D1', 'D1'), ('D2', 'D2'), ('D3', 'D3'), ('D4', 'D4')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='showchart',
            name='payment_mode',
            field=models.CharField(choices=[('chegue', 'chegue'), ('card', 'card'), ('cash', 'cash'), ('online', 'online'), ('draft', 'draft')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='showchart',
            name='region',
            field=models.CharField(choices=[('R1', 'R1'), ('R2', 'R2'), ('R3', 'R3')], max_length=2, null=True),
        ),
    ]
